# Generated by Django 5.0 on 2023-12-15 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addres',
            name='user',
        ),
    ]
